# sets the --env flag by default. This value is actually a file since the `switch`
# subcommand can change this value to switch contexts.
default_environment = ".env"

# Collection is a set of run template, where you specify the environment and the
# template you want to run.
#collection = "collection/"

# You can specify multiple configuration directories to use at runtime as well. The
# [[config]] table has two values:
# dir: A directory where all toml will be merged into the config
# path: A single file to be loaded into config
# only one of these values can be used in a single definition
# 
# ```toml
# # valid
# [[config]]
#   path = "/etc/kla/second_file.toml"
# 
# # valid
# [[config]]
#   dir = "/etc/kla/config.d"
# 
# # invalid
# [[config]]
#   dir = "/etc/kla/config.d"
#   path = "/etc/kla/second_file.toml"
# 
# # invalid
# [[config]]
#   my_random_attribute = "something"
# ```
[[config]]
type = "dir"
path = "conf.d/"

extension_dir = ".extensions/"
