# environments are specified in the config!
[[environment]]
name = "poetry"
url = "https://poetrydb.org/"
short_description = "Poetry by authors"
# The template directory is where template are for this context which can be
# used with `run`
template_dir = "tmpl/"

  [environment.settings.auth]
    type = "basic"
    username = "test"
    password = "something"

