# Just like templates, collections get turned into clap commands, so you can
# specify description text to help derive the `help` output.
short_description = "This is a short description and will show up when running `kla bulk`"
description = """
This is a much longer description, that will show up when you run `kla bulk example --help` so it can go into much more detail about what this does and how it does it, pretty darn cool aint it!
"""

# Just like a template, a collection can also take an arguments. They work the
# same as arguments
[[arg]]
  name = "author"
  help = "The author you want to look into"

# Here we specify the first group, a group is made up of multiple environments
# that we want to run a shared template against. All of these environments must
# have any templates defined
[[group]]
  environments = [
    "poetry",
    "poetry",
  ]

# Within `group.template` you can specify multiple templates. Each of these templates
# will be run sequentially per environment, but concurrently between environments. Here
# we are using the supplied argument to set the author template argument.
[[group.template]]
  name = "author"
  args = ["{{ author }}"]

# You can call the same template multiple times, here you can see we always want to call for
# William Shakespeare, regardless of input
[[group.template]]
  name = "author"
  args = ["William Shakespeare"]

# When run, this template will generate 4 http requests

# You can specify more than one group though! so let's do it
[[group]]
  environments = [
    "poetry",
  ]

  [[group.template]]
    name = "author"
    args = ["Thomas Gray"]
