name: deploy

permissions:
  contents: write

on:
  push:
    tags:
      - "*.*.*"
env:
  CARGO_TERM_COLOR: always

jobs:
  build_bin:
    strategy:
      matrix:
        builds:
          - image: ubuntu-latest
            arch: x86_64
          - image: macos-latest
            arch: aarch64-apple
          - image: macos-15-intel
            arch: x86_64-apple
    if: github.ref_type == 'tag' # only run when this workflow was triggered by a tag push
    runs-on: "${{ matrix.builds.image }}"
    steps:
      - uses: actions/checkout@v4
      - run: rustup update
      - run: cargo install set-cargo-version
      - run: "set-cargo-version ./Cargo.toml ${{ github.event.release.tag_name }}"
      - run: cargo build --release
      - run: mv "target/release/kla" "target/release/kla-${{ matrix.builds.arch }}-${{ github.event.release.tag_name }}"
      - uses: actions/upload-artifact@v4
        with:
          name: "kla-${{ matrix.builds.arch }}-${{ github.ref_name }}"
          path: "target/release/kla-${{ matrix.builds.arch }}-${{ github.ref_name }}"
          if-no-files-found: error

  publish_release:
    runs-on: ubuntu-latest
    needs: build_bin # waits for all matrix builds to finish
    if: github.ref_type == 'tag' # only run when this workflow was triggered by a tag push
    steps:
      - name: Download all build artifacts
        # omit 'name' to download ALL artifacts created by previous job(s)
        uses: actions/download-artifact@v4

      - name: List files (debug)
        run: |
          echo "cwd: $(pwd)"
          find . -maxdepth 3 -type f -print

      - name: Create or update GitHub release and upload assets
        uses: softprops/action-gh-release@v2
        with:
          # newline-separated globs — upload any kla binary found in downloaded artifact dirs
          files: |
            **/kla-*
  homebrew:
    runs-on: ubuntu-latest
    needs: publish_release
    if: github.ref_type == 'tag' # only run when this workflow was triggered by a tag push
    steps:
      - name: Bump Formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          # A Personal Access Token (PAT) is required to push to Homebrew taps
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          
          # Name of your formula (e.g., your-cli-tool)
          formula: kla
          
          # Your custom Homebrew Tap repository (e.g., username/homebrew-tap)
          tap: d1ngd0/homebrew-tap
